sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only

#=== 【Travis CI】 private-dependencies → api-token === (start)
## Docs: https://docs.travis-ci.com/user/private-dependencies/#api-token
git:
  submodules: false
before_install:
  - echo -e "\n\nmachine github.com\n login $GH_TOKEN\n" >~/.netrc
  - git submodule update --init --recursive
#=== 【Travis CI】 private-dependencies → api-token === (end)

script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  # [[译] Hexo git deployer 删除了提交历史记录该怎么整？](https://segmentfault.com/a/1190000018024460#)
  script: sh _deploy/deploy.sh
  on:
    branch: master
  local-dir: public

# Cache
## [Cache - config.travis-ci.com)](https://config.travis-ci.com/ref/job/cache)
cache:
  directories:
  - $HOME/.m2